### ISSUE TITLE
[Bug]: GET packages doesnt work in new version

### ISSUE THREAD

**Issue by hadifar** [eclipse-aaspe/server#358] opened 2024-11-13 13:58 UTC
In latest version of the server get packages doesn't  work therefore we caanot connect to HTTP/REST repository

```
curl -X 'GET' \
  'http://localhost:5001/packages' \
  -H 'accept: text/plain'
```

### To reproduce

Download the latest version (AasxServerBlazor.v0.3.1.172-aasV3-alpha-latest),
Unzip and execute the following command:

`dotnet AasxServerBlazor.dll --no-security --edit --read-temp --data-path .\aasxs --external-blazor http://127.0.0.1`

Then go to `http://localhost:5001/packages`

![image](https://github.com/user-attachments/assets/2b012343-c107-47f5-88e3-9e050f1c2605)

It gives 400 (bad request)

### Expected Behaviour

In the previous versions (e.g., AasxServerBlazor.2023-11-17.alpha) it did work.

### Version

AasxServerBlazor.v0.3.1.172-aasV3-alpha-latest

### Operating System

Windows

**Comment by juileetikekar** [comment] 2024-11-14 13:44
Duplicate of #359, #321, #340

**Closed** 2024-11-14 15:16 UTC
Labels: bug
